//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace IntegracaoPsP.Domain.Entities
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fichaRegistroParceiroJV {
        
        private int numeroDuvField;
        
        private int numeroViagemField;
        
        private fichaRegistroParceiroJVAgenteMaritimo agenteMaritimoField;
        
        /// <remarks/>
        public int numeroDuv {
            get {
                return this.numeroDuvField;
            }
            set {
                this.numeroDuvField = value;
            }
        }
        
        /// <remarks/>
        public int numeroViagem {
            get {
                return this.numeroViagemField;
            }
            set {
                this.numeroViagemField = value;
            }
        }
        
        /// <remarks/>
        public fichaRegistroParceiroJVAgenteMaritimo agenteMaritimo {
            get {
                return this.agenteMaritimoField;
            }
            set {
                this.agenteMaritimoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaRegistroParceiroJVAgenteMaritimo {
        
        private string nomeAgenciaField;
        
        private long cnpjAgenciaNavegacaoField;
        
        private fichaRegistroParceiroJVAgenteMaritimoCnpjJointVentureAutorizada[] cnpjJointVenturesAutorizadasField;
        
        /// <remarks/>
        public string nomeAgencia {
            get {
                return this.nomeAgenciaField;
            }
            set {
                this.nomeAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public long cnpjAgenciaNavegacao {
            get {
                return this.cnpjAgenciaNavegacaoField;
            }
            set {
                this.cnpjAgenciaNavegacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("cnpjJointVentureAutorizada", IsNullable=false)]
        public fichaRegistroParceiroJVAgenteMaritimoCnpjJointVentureAutorizada[] cnpjJointVenturesAutorizadas {
            get {
                return this.cnpjJointVenturesAutorizadasField;
            }
            set {
                this.cnpjJointVenturesAutorizadasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaRegistroParceiroJVAgenteMaritimoCnpjJointVentureAutorizada {
        
        private long cnpjField;
        
        private string tipoTrafegoField;
        
        /// <remarks/>
        public long cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        public string tipoTrafego {
            get {
                return this.tipoTrafegoField;
            }
            set {
                this.tipoTrafegoField = value;
            }
        }
    }
}
