//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace IntegracaoPsP.Domain.Entities.AvisoAtracacao
{
    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fichaAvisoAtracacao {
        
        private string dataHoraSistemaField;
        
        private string numeroDuvField;
        
        private string portoEstadiaField;
        
        private string assumeEstadiaField;
        
        private string duracaoInferior24hField;
        
        private string dataHoraPrevistaAtracacaoField;
        
        private locaisPrevistosAtracacaoLocalPrevistoAtracacao[] locaisPrevistosAtracacaoField;
        
        private fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao[] fundeadourosPrevistosAtracacaoField;
        
        private string dataHoraPrevistaDesatracacaoField;
        
        private string ultimoPortoEscalaField;
        
        private string proximoPortoEscalaField;
        
        private agenteMaritimo agenteMaritimoField;
        
        private FichaDadosEmbarcacao avisoAtracacaoField;
        
        private embarcacao embarcacaoField;
        
        private estadiaEmbarcacao estadiaEmbarcacaoField;
        
        private ratificacoesOperadorRatificacaoOperador[] ratificacoesOperadorField;
        
        /// <remarks/>
        public string dataHoraSistema {
            get {
                return this.dataHoraSistemaField;
            }
            set {
                this.dataHoraSistemaField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDuv {
            get {
                return this.numeroDuvField;
            }
            set {
                this.numeroDuvField = value;
            }
        }
        
        /// <remarks/>
        public string portoEstadia {
            get {
                return this.portoEstadiaField;
            }
            set {
                this.portoEstadiaField = value;
            }
        }
        
        /// <remarks/>
        public string assumeEstadia {
            get {
                return this.assumeEstadiaField;
            }
            set {
                this.assumeEstadiaField = value;
            }
        }
        
        /// <remarks/>
        public string duracaoInferior24h {
            get {
                return this.duracaoInferior24hField;
            }
            set {
                this.duracaoInferior24hField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaAtracacao {
            get {
                return this.dataHoraPrevistaAtracacaoField;
            }
            set {
                this.dataHoraPrevistaAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("localPrevistoAtracacao", IsNullable=false)]
        public locaisPrevistosAtracacaoLocalPrevistoAtracacao[] locaisPrevistosAtracacao {
            get {
                return this.locaisPrevistosAtracacaoField;
            }
            set {
                this.locaisPrevistosAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("fundeadouroPrevistoAtracacao", IsNullable=false)]
        public fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao[] fundeadourosPrevistosAtracacao {
            get {
                return this.fundeadourosPrevistosAtracacaoField;
            }
            set {
                this.fundeadourosPrevistosAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaDesatracacao {
            get {
                return this.dataHoraPrevistaDesatracacaoField;
            }
            set {
                this.dataHoraPrevistaDesatracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string ultimoPortoEscala {
            get {
                return this.ultimoPortoEscalaField;
            }
            set {
                this.ultimoPortoEscalaField = value;
            }
        }
        
        /// <remarks/>
        public string proximoPortoEscala {
            get {
                return this.proximoPortoEscalaField;
            }
            set {
                this.proximoPortoEscalaField = value;
            }
        }
        
        /// <remarks/>
        public agenteMaritimo agenteMaritimo {
            get {
                return this.agenteMaritimoField;
            }
            set {
                this.agenteMaritimoField = value;
            }
        }
        
        /// <remarks/>
        public FichaDadosEmbarcacao avisoAtracacao {
            get {
                return this.avisoAtracacaoField;
            }
            set {
                this.avisoAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public embarcacao embarcacao {
            get {
                return this.embarcacaoField;
            }
            set {
                this.embarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public estadiaEmbarcacao estadiaEmbarcacao {
            get {
                return this.estadiaEmbarcacaoField;
            }
            set {
                this.estadiaEmbarcacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ratificacaoOperador", IsNullable=false)]
        public ratificacoesOperadorRatificacaoOperador[] ratificacoesOperador {
            get {
                return this.ratificacoesOperadorField;
            }
            set {
                this.ratificacoesOperadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class locaisPrevistosAtracacaoLocalPrevistoAtracacao {
        
        private string areaPortoField;
        
        private string bercoField;
        
        /// <remarks/>
        public string areaPorto {
            get {
                return this.areaPortoField;
            }
            set {
                this.areaPortoField = value;
            }
        }
        
        /// <remarks/>
        public string berco {
            get {
                return this.bercoField;
            }
            set {
                this.bercoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao {
        
        private string fundeadouroField;
        
        private string boiaAmarracaoField;
        
        /// <remarks/>
        public string fundeadouro {
            get {
                return this.fundeadouroField;
            }
            set {
                this.fundeadouroField = value;
            }
        }
        
        /// <remarks/>
        public string boiaAmarracao {
            get {
                return this.boiaAmarracaoField;
            }
            set {
                this.boiaAmarracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class agenteMaritimo {
        
        private string nomeAgenciaField;
        
        private string cnpjAgenciaNavegacaoField;
        
        /// <remarks/>
        public string nomeAgencia {
            get {
                return this.nomeAgenciaField;
            }
            set {
                this.nomeAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string cnpjAgenciaNavegacao {
            get {
                return this.cnpjAgenciaNavegacaoField;
            }
            set {
                this.cnpjAgenciaNavegacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FichaDadosEmbarcacao {
        
        private string dataHoraEsperadaField;
        
        private string cargaPerigosaField;
        
        private string qtdeConteineresField;
        
        private string pesoCargaField;
        
        /// <remarks/>
        public string dataHoraEsperada {
            get {
                return this.dataHoraEsperadaField;
            }
            set {
                this.dataHoraEsperadaField = value;
            }
        }
        
        /// <remarks/>
        public string cargaPerigosa {
            get {
                return this.cargaPerigosaField;
            }
            set {
                this.cargaPerigosaField = value;
            }
        }
        
        /// <remarks/>
        public string qtdeConteineres {
            get {
                return this.qtdeConteineresField;
            }
            set {
                this.qtdeConteineresField = value;
            }
        }
        
        /// <remarks/>
        public string pesoCarga {
            get {
                return this.pesoCargaField;
            }
            set {
                this.pesoCargaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class embarcacao {
        
        private string numeroIMOField;
        
        private string inscricaoField;
        
        private string nomeEmbarcacaoField;
        
        private string estadoBandeiraField;
        
        private string caladoMaximoField;
        
        private string caladoEntradaProaField;
        
        private string caladoEntradaPopaField;
        
        private string caladoSaidaProaField;
        
        private string caladoSaidaPopaField;
        
        /// <remarks/>
        public string numeroIMO {
            get {
                return this.numeroIMOField;
            }
            set {
                this.numeroIMOField = value;
            }
        }
        
        /// <remarks/>
        public string inscricao {
            get {
                return this.inscricaoField;
            }
            set {
                this.inscricaoField = value;
            }
        }
        
        /// <remarks/>
        public string nomeEmbarcacao {
            get {
                return this.nomeEmbarcacaoField;
            }
            set {
                this.nomeEmbarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public string estadoBandeira {
            get {
                return this.estadoBandeiraField;
            }
            set {
                this.estadoBandeiraField = value;
            }
        }
        
        /// <remarks/>
        public string caladoMaximo {
            get {
                return this.caladoMaximoField;
            }
            set {
                this.caladoMaximoField = value;
            }
        }
        
        /// <remarks/>
        public string caladoEntradaProa {
            get {
                return this.caladoEntradaProaField;
            }
            set {
                this.caladoEntradaProaField = value;
            }
        }
        
        /// <remarks/>
        public string caladoEntradaPopa {
            get {
                return this.caladoEntradaPopaField;
            }
            set {
                this.caladoEntradaPopaField = value;
            }
        }
        
        /// <remarks/>
        public string caladoSaidaProa {
            get {
                return this.caladoSaidaProaField;
            }
            set {
                this.caladoSaidaProaField = value;
            }
        }
        
        /// <remarks/>
        public string caladoSaidaPopa {
            get {
                return this.caladoSaidaPopaField;
            }
            set {
                this.caladoSaidaPopaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class estadiaEmbarcacao {
        
        private string prioridadePretendidaField;
        
        private string qtdeDiasPrevistosOperacaoField;
        
        private string numeroViagemAgenciaField;
        
        private tipoViagemEnum tipoViagemField;
        
        private string tipoCargaField;
        
        private string destinoCargaField;
        
        private string quantidadeFlutuantesField;
        
        private string quantidadePranchasField;
        
        /// <remarks/>
        public string prioridadePretendida {
            get {
                return this.prioridadePretendidaField;
            }
            set {
                this.prioridadePretendidaField = value;
            }
        }
        
        /// <remarks/>
        public string qtdeDiasPrevistosOperacao {
            get {
                return this.qtdeDiasPrevistosOperacaoField;
            }
            set {
                this.qtdeDiasPrevistosOperacaoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroViagemAgencia {
            get {
                return this.numeroViagemAgenciaField;
            }
            set {
                this.numeroViagemAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public tipoViagemEnum tipoViagem {
            get {
                return this.tipoViagemField;
            }
            set {
                this.tipoViagemField = value;
            }
        }
        
        /// <remarks/>
        public string tipoCarga {
            get {
                return this.tipoCargaField;
            }
            set {
                this.tipoCargaField = value;
            }
        }
        
        /// <remarks/>
        public string destinoCarga {
            get {
                return this.destinoCargaField;
            }
            set {
                this.destinoCargaField = value;
            }
        }
        
        /// <remarks/>
        public string quantidadeFlutuantes {
            get {
                return this.quantidadeFlutuantesField;
            }
            set {
                this.quantidadeFlutuantesField = value;
            }
        }
        
        /// <remarks/>
        public string quantidadePranchas {
            get {
                return this.quantidadePranchasField;
            }
            set {
                this.quantidadePranchasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum tipoViagemEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ratificacoesOperadorRatificacaoOperador {
        
        private string operadorField;
        
        private string nomeOperadorField;
        
        private string operacaoContratadaField;
        
        private string contratoCodespField;
        
        private string numeroContratoField;
        
        private string qtdePeriodosField;
        
        private string destinoProcedenciaCargaField;
        
        private embalagensEnum embalagemField;
        
        private bool embalagemFieldSpecified;
        
        private string mercadoriaField;
        
        private locaisOperacaoPortoLocalOperacaoPorto[] locaisOperacaoPortoField;
        
        private fundeadourosOperacaoPortoFundeadouroOperacaoPorto[] fundeadourosOperacaoPortoField;
        
        private string qtdeConteineresField;
        
        private string pesoField;
        
        private tipoFaturamentoEnum[] tiposFaturamentoOperadorField;
        
        private tipoFaturamentoEnum[] tiposFaturamentoAgenciaField;
        
        private tipoFaturamentoEnum[] tiposFaturamentoArmadorField;
        
        /// <remarks/>
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public string nomeOperador {
            get {
                return this.nomeOperadorField;
            }
            set {
                this.nomeOperadorField = value;
            }
        }
        
        /// <remarks/>
        public string operacaoContratada {
            get {
                return this.operacaoContratadaField;
            }
            set {
                this.operacaoContratadaField = value;
            }
        }
        
        /// <remarks/>
        public string contratoCodesp {
            get {
                return this.contratoCodespField;
            }
            set {
                this.contratoCodespField = value;
            }
        }
        
        /// <remarks/>
        public string numeroContrato {
            get {
                return this.numeroContratoField;
            }
            set {
                this.numeroContratoField = value;
            }
        }
        
        /// <remarks/>
        public string qtdePeriodos {
            get {
                return this.qtdePeriodosField;
            }
            set {
                this.qtdePeriodosField = value;
            }
        }
        
        /// <remarks/>
        public string destinoProcedenciaCarga {
            get {
                return this.destinoProcedenciaCargaField;
            }
            set {
                this.destinoProcedenciaCargaField = value;
            }
        }
        
        /// <remarks/>
        public embalagensEnum embalagem {
            get {
                return this.embalagemField;
            }
            set {
                this.embalagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool embalagemSpecified {
            get {
                return this.embalagemFieldSpecified;
            }
            set {
                this.embalagemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string mercadoria {
            get {
                return this.mercadoriaField;
            }
            set {
                this.mercadoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("localOperacaoPorto", IsNullable=false)]
        public locaisOperacaoPortoLocalOperacaoPorto[] locaisOperacaoPorto {
            get {
                return this.locaisOperacaoPortoField;
            }
            set {
                this.locaisOperacaoPortoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("fundeadouroOperacaoPorto", IsNullable=false)]
        public fundeadourosOperacaoPortoFundeadouroOperacaoPorto[] fundeadourosOperacaoPorto {
            get {
                return this.fundeadourosOperacaoPortoField;
            }
            set {
                this.fundeadourosOperacaoPortoField = value;
            }
        }
        
        /// <remarks/>
        public string qtdeConteineres {
            get {
                return this.qtdeConteineresField;
            }
            set {
                this.qtdeConteineresField = value;
            }
        }
        
        /// <remarks/>
        public string peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("tipoFaturamentoOperador", IsNullable=false)]
        public tipoFaturamentoEnum[] tiposFaturamentoOperador {
            get {
                return this.tiposFaturamentoOperadorField;
            }
            set {
                this.tiposFaturamentoOperadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("tipoFaturamentoAgencia", IsNullable=false)]
        public tipoFaturamentoEnum[] tiposFaturamentoAgencia {
            get {
                return this.tiposFaturamentoAgenciaField;
            }
            set {
                this.tiposFaturamentoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("tipoFaturamentoArmador", IsNullable=false)]
        public tipoFaturamentoEnum[] tiposFaturamentoArmador {
            get {
                return this.tiposFaturamentoArmadorField;
            }
            set {
                this.tiposFaturamentoArmadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum embalagensEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28")]
        Item28,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("29")]
        Item29,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("34")]
        Item34,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("36")]
        Item36,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37")]
        Item37,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("39")]
        Item39,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("45")]
        Item45,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("46")]
        Item46,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("47")]
        Item47,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("48")]
        Item48,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("49")]
        Item49,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("51")]
        Item51,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("52")]
        Item52,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("54")]
        Item54,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("56")]
        Item56,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("57")]
        Item57,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("58")]
        Item58,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("59")]
        Item59,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("62")]
        Item62,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("63")]
        Item63,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("64")]
        Item64,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("65")]
        Item65,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("66")]
        Item66,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("67")]
        Item67,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("68")]
        Item68,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("69")]
        Item69,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("71")]
        Item71,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("72")]
        Item72,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("73")]
        Item73,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("74")]
        Item74,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("98")]
        Item98,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class locaisOperacaoPortoLocalOperacaoPorto {
        
        private string areaPortoField;
        
        private string bercoField;
        
        /// <remarks/>
        public string areaPorto {
            get {
                return this.areaPortoField;
            }
            set {
                this.areaPortoField = value;
            }
        }
        
        /// <remarks/>
        public string berco {
            get {
                return this.bercoField;
            }
            set {
                this.bercoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fundeadourosOperacaoPortoFundeadouroOperacaoPorto {
        
        private string fundeadouroField;
        
        private string boiaAmarracaoField;
        
        /// <remarks/>
        public string fundeadouro {
            get {
                return this.fundeadouroField;
            }
            set {
                this.fundeadouroField = value;
            }
        }
        
        /// <remarks/>
        public string boiaAmarracao {
            get {
                return this.boiaAmarracaoField;
            }
            set {
                this.boiaAmarracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum tipoFaturamentoEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela I")]
        TabelaI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela II")]
        TabelaII,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela III")]
        TabelaIII,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela VI")]
        TabelaVI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela I 1.1")]
        TabelaI11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela I 1.2")]
        TabelaI12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela II 2.1")]
        TabelaII21,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela IV")]
        TabelaIV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela V")]
        TabelaV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tabela VII")]
        TabelaVII,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class locaisPrevistosAtracacao {
        
        private locaisPrevistosAtracacaoLocalPrevistoAtracacao[] localPrevistoAtracacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("localPrevistoAtracacao")]
        public locaisPrevistosAtracacaoLocalPrevistoAtracacao[] localPrevistoAtracacao {
            get {
                return this.localPrevistoAtracacaoField;
            }
            set {
                this.localPrevistoAtracacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fundeadourosPrevistosAtracacao {
        
        private fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao[] fundeadouroPrevistoAtracacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fundeadouroPrevistoAtracacao")]
        public fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao[] fundeadouroPrevistoAtracacao {
            get {
                return this.fundeadouroPrevistoAtracacaoField;
            }
            set {
                this.fundeadouroPrevistoAtracacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ratificacoesOperador {
        
        private ratificacoesOperadorRatificacaoOperador[] ratificacaoOperadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ratificacaoOperador")]
        public ratificacoesOperadorRatificacaoOperador[] ratificacaoOperador {
            get {
                return this.ratificacaoOperadorField;
            }
            set {
                this.ratificacaoOperadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class locaisOperacaoPorto {
        
        private locaisOperacaoPortoLocalOperacaoPorto[] localOperacaoPortoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("localOperacaoPorto")]
        public locaisOperacaoPortoLocalOperacaoPorto[] localOperacaoPorto {
            get {
                return this.localOperacaoPortoField;
            }
            set {
                this.localOperacaoPortoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fundeadourosOperacaoPorto {
        
        private fundeadourosOperacaoPortoFundeadouroOperacaoPorto[] fundeadouroOperacaoPortoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fundeadouroOperacaoPorto")]
        public fundeadourosOperacaoPortoFundeadouroOperacaoPorto[] fundeadouroOperacaoPorto {
            get {
                return this.fundeadouroOperacaoPortoField;
            }
            set {
                this.fundeadouroOperacaoPortoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class tiposFaturamentoOperador {
        
        private tipoFaturamentoEnum[] tipoFaturamentoOperadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoFaturamentoOperador")]
        public tipoFaturamentoEnum[] tipoFaturamentoOperador {
            get {
                return this.tipoFaturamentoOperadorField;
            }
            set {
                this.tipoFaturamentoOperadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class tiposFaturamentoAgencia {
        
        private tipoFaturamentoEnum[] tipoFaturamentoAgenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoFaturamentoAgencia")]
        public tipoFaturamentoEnum[] tipoFaturamentoAgencia {
            get {
                return this.tipoFaturamentoAgenciaField;
            }
            set {
                this.tipoFaturamentoAgenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class tiposFaturamentoArmador {
        
        private tipoFaturamentoEnum[] tipoFaturamentoArmadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoFaturamentoArmador")]
        public tipoFaturamentoEnum[] tipoFaturamentoArmador {
            get {
                return this.tipoFaturamentoArmadorField;
            }
            set {
                this.tipoFaturamentoArmadorField = value;
            }
        }
    }
}
