//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace IntegracaoPsP.Domain.Entities.AvisoAtracacaoUsoCanal
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fichaAvisoAtracacaoUsoCanal {
        
        private string dataHoraSistemaField;
        
        private string numeroDuvField;
        
        private string portoEstadiaField;
        
        private string dataHoraPrevistaAtracacaoField;
        
        private locaisPrevistosAtracacaoLocalPrevistoAtracacao[] locaisPrevistosAtracacaoField;
        
        private fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao[] fundeadourosPrevistosAtracacaoField;
        
        private string dataHoraPrevistaDesatracacaoField;
        
        private string localPrevistoAtracacaoUsoCanalField;
        
        private string motivoUsoCanalField;
        
        private string outroMotivoUsoCanalField;
        
        private agenteMaritimo agenteMaritimoField;
        
        private embarcacao embarcacaoField;
        
        /// <remarks/>
        public string dataHoraSistema {
            get {
                return this.dataHoraSistemaField;
            }
            set {
                this.dataHoraSistemaField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDuv {
            get {
                return this.numeroDuvField;
            }
            set {
                this.numeroDuvField = value;
            }
        }
        
        /// <remarks/>
        public string portoEstadia {
            get {
                return this.portoEstadiaField;
            }
            set {
                this.portoEstadiaField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaAtracacao {
            get {
                return this.dataHoraPrevistaAtracacaoField;
            }
            set {
                this.dataHoraPrevistaAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("localPrevistoAtracacao", IsNullable=false)]
        public locaisPrevistosAtracacaoLocalPrevistoAtracacao[] locaisPrevistosAtracacao {
            get {
                return this.locaisPrevistosAtracacaoField;
            }
            set {
                this.locaisPrevistosAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("fundeadouroPrevistoAtracacao", IsNullable=false)]
        public fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao[] fundeadourosPrevistosAtracacao {
            get {
                return this.fundeadourosPrevistosAtracacaoField;
            }
            set {
                this.fundeadourosPrevistosAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaDesatracacao {
            get {
                return this.dataHoraPrevistaDesatracacaoField;
            }
            set {
                this.dataHoraPrevistaDesatracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string localPrevistoAtracacaoUsoCanal {
            get {
                return this.localPrevistoAtracacaoUsoCanalField;
            }
            set {
                this.localPrevistoAtracacaoUsoCanalField = value;
            }
        }
        
        /// <remarks/>
        public string motivoUsoCanal {
            get {
                return this.motivoUsoCanalField;
            }
            set {
                this.motivoUsoCanalField = value;
            }
        }
        
        /// <remarks/>
        public string outroMotivoUsoCanal {
            get {
                return this.outroMotivoUsoCanalField;
            }
            set {
                this.outroMotivoUsoCanalField = value;
            }
        }
        
        /// <remarks/>
        public agenteMaritimo agenteMaritimo {
            get {
                return this.agenteMaritimoField;
            }
            set {
                this.agenteMaritimoField = value;
            }
        }
        
        /// <remarks/>
        public embarcacao embarcacao {
            get {
                return this.embarcacaoField;
            }
            set {
                this.embarcacaoField = value;
            }
        }
    }
    
    
    public partial class locaisPrevistosAtracacaoLocalPrevistoAtracacao {
        
        private string areaPortoField;
        
        private string bercoField;
        
        /// <remarks/>
        public string areaPorto {
            get {
                return this.areaPortoField;
            }
            set {
                this.areaPortoField = value;
            }
        }
        
        /// <remarks/>
        public string berco {
            get {
                return this.bercoField;
            }
            set {
                this.bercoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao {
        
        private string fundeadouroField;
        
        private string boiaAmarracaoField;
        
        /// <remarks/>
        public string fundeadouro {
            get {
                return this.fundeadouroField;
            }
            set {
                this.fundeadouroField = value;
            }
        }
        
        /// <remarks/>
        public string boiaAmarracao {
            get {
                return this.boiaAmarracaoField;
            }
            set {
                this.boiaAmarracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class agenteMaritimo {
        
        private string nomeAgenciaField;
        
        private string cnpjAgenciaNavegacaoField;
        
        /// <remarks/>
        public string nomeAgencia {
            get {
                return this.nomeAgenciaField;
            }
            set {
                this.nomeAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string cnpjAgenciaNavegacao {
            get {
                return this.cnpjAgenciaNavegacaoField;
            }
            set {
                this.cnpjAgenciaNavegacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class embarcacao {
        
        private string numeroIMOField;
        
        private string inscricaoField;
        
        private string nomeEmbarcacaoField;
        
        private string estadoBandeiraField;
        
        private string caladoEntradaProaField;
        
        private string caladoEntradaPopaField;
        
        private string caladoSaidaProaField;
        
        private string caladoSaidaPopaField;
        
        /// <remarks/>
        public string numeroIMO {
            get {
                return this.numeroIMOField;
            }
            set {
                this.numeroIMOField = value;
            }
        }
        
        /// <remarks/>
        public string inscricao {
            get {
                return this.inscricaoField;
            }
            set {
                this.inscricaoField = value;
            }
        }
        
        /// <remarks/>
        public string nomeEmbarcacao {
            get {
                return this.nomeEmbarcacaoField;
            }
            set {
                this.nomeEmbarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public string estadoBandeira {
            get {
                return this.estadoBandeiraField;
            }
            set {
                this.estadoBandeiraField = value;
            }
        }
        
        /// <remarks/>
        public string caladoEntradaProa {
            get {
                return this.caladoEntradaProaField;
            }
            set {
                this.caladoEntradaProaField = value;
            }
        }
        
        /// <remarks/>
        public string caladoEntradaPopa {
            get {
                return this.caladoEntradaPopaField;
            }
            set {
                this.caladoEntradaPopaField = value;
            }
        }
        
        /// <remarks/>
        public string caladoSaidaProa {
            get {
                return this.caladoSaidaProaField;
            }
            set {
                this.caladoSaidaProaField = value;
            }
        }
        
        /// <remarks/>
        public string caladoSaidaPopa {
            get {
                return this.caladoSaidaPopaField;
            }
            set {
                this.caladoSaidaPopaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class locaisPrevistosAtracacao {
        
        private locaisPrevistosAtracacaoLocalPrevistoAtracacao[] localPrevistoAtracacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("localPrevistoAtracacao")]
        public locaisPrevistosAtracacaoLocalPrevistoAtracacao[] localPrevistoAtracacao {
            get {
                return this.localPrevistoAtracacaoField;
            }
            set {
                this.localPrevistoAtracacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fundeadourosPrevistosAtracacao {
        
        private fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao[] fundeadouroPrevistoAtracacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fundeadouroPrevistoAtracacao")]
        public fundeadourosPrevistosAtracacaoFundeadouroPrevistoAtracacao[] fundeadouroPrevistoAtracacao {
            get {
                return this.fundeadouroPrevistoAtracacaoField;
            }
            set {
                this.fundeadouroPrevistoAtracacaoField = value;
            }
        }
    }
}
