//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace IntegracaoPsP.Domain.Entities
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fichaAvisoAtracacao {
        
        private string dataHoraSistemaField;
        
        private int numeroDuvField;
        
        private string portoEstadiaField;
        
        private string assumeEstadiaField;
        
        private string duracaoInferior24hField;
        
        private string dataHoraPrevistaAtracacaoField;
        
        private fichaAvisoAtracacaoLocaisPrevistosAtracacao locaisPrevistosAtracacaoField;
        
        private string fundeadourosPrevistosAtracacaoField;
        
        private string dataHoraPrevistaDesatracacaoField;
        
        private string ultimoPortoEscalaField;
        
        private string proximoPortoEscalaField;
        
        private fichaAvisoAtracacaoAgenteMaritimo agenteMaritimoField;
        
        private fichaAvisoAtracacaoAvisoAtracacao avisoAtracacaoField;
        
        private fichaAvisoAtracacaoEmbarcacao embarcacaoField;
        
        private fichaAvisoAtracacaoEstadiaEmbarcacao estadiaEmbarcacaoField;
        
        private fichaAvisoAtracacaoRepresentanteLegal representanteLegalField;
        
        private fichaAvisoAtracacaoRatificacoesOperador ratificacoesOperadorField;
        
        /// <remarks/>
        public string dataHoraSistema {
            get {
                return this.dataHoraSistemaField;
            }
            set {
                this.dataHoraSistemaField = value;
            }
        }
        
        /// <remarks/>
        public int numeroDuv {
            get {
                return this.numeroDuvField;
            }
            set {
                this.numeroDuvField = value;
            }
        }
        
        /// <remarks/>
        public string portoEstadia {
            get {
                return this.portoEstadiaField;
            }
            set {
                this.portoEstadiaField = value;
            }
        }
        
        /// <remarks/>
        public string assumeEstadia {
            get {
                return this.assumeEstadiaField;
            }
            set {
                this.assumeEstadiaField = value;
            }
        }
        
        /// <remarks/>
        public string duracaoInferior24h {
            get {
                return this.duracaoInferior24hField;
            }
            set {
                this.duracaoInferior24hField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaAtracacao {
            get {
                return this.dataHoraPrevistaAtracacaoField;
            }
            set {
                this.dataHoraPrevistaAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaAvisoAtracacaoLocaisPrevistosAtracacao locaisPrevistosAtracacao {
            get {
                return this.locaisPrevistosAtracacaoField;
            }
            set {
                this.locaisPrevistosAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string fundeadourosPrevistosAtracacao {
            get {
                return this.fundeadourosPrevistosAtracacaoField;
            }
            set {
                this.fundeadourosPrevistosAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaDesatracacao {
            get {
                return this.dataHoraPrevistaDesatracacaoField;
            }
            set {
                this.dataHoraPrevistaDesatracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string ultimoPortoEscala {
            get {
                return this.ultimoPortoEscalaField;
            }
            set {
                this.ultimoPortoEscalaField = value;
            }
        }
        
        /// <remarks/>
        public string proximoPortoEscala {
            get {
                return this.proximoPortoEscalaField;
            }
            set {
                this.proximoPortoEscalaField = value;
            }
        }
        
        /// <remarks/>
        public fichaAvisoAtracacaoAgenteMaritimo agenteMaritimo {
            get {
                return this.agenteMaritimoField;
            }
            set {
                this.agenteMaritimoField = value;
            }
        }
        
        /// <remarks/>
        public fichaAvisoAtracacaoAvisoAtracacao avisoAtracacao {
            get {
                return this.avisoAtracacaoField;
            }
            set {
                this.avisoAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaAvisoAtracacaoEmbarcacao embarcacao {
            get {
                return this.embarcacaoField;
            }
            set {
                this.embarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaAvisoAtracacaoEstadiaEmbarcacao estadiaEmbarcacao {
            get {
                return this.estadiaEmbarcacaoField;
            }
            set {
                this.estadiaEmbarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaAvisoAtracacaoRepresentanteLegal representanteLegal {
            get {
                return this.representanteLegalField;
            }
            set {
                this.representanteLegalField = value;
            }
        }
        
        /// <remarks/>
        public fichaAvisoAtracacaoRatificacoesOperador ratificacoesOperador {
            get {
                return this.ratificacoesOperadorField;
            }
            set {
                this.ratificacoesOperadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoLocaisPrevistosAtracacao {
        
        private fichaAvisoAtracacaoLocaisPrevistosAtracacaoLocalPrevistoAtracacao localPrevistoAtracacaoField;
        
        /// <remarks/>
        public fichaAvisoAtracacaoLocaisPrevistosAtracacaoLocalPrevistoAtracacao localPrevistoAtracacao {
            get {
                return this.localPrevistoAtracacaoField;
            }
            set {
                this.localPrevistoAtracacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoLocaisPrevistosAtracacaoLocalPrevistoAtracacao {
        
        private string areaPortoField;
        
        private short bercoField;
        
        private long cnpjArrendatarioField;
        
        /// <remarks/>
        public string areaPorto {
            get {
                return this.areaPortoField;
            }
            set {
                this.areaPortoField = value;
            }
        }
        
        /// <remarks/>
        public short berco {
            get {
                return this.bercoField;
            }
            set {
                this.bercoField = value;
            }
        }
        
        /// <remarks/>
        public long cnpjArrendatario {
            get {
                return this.cnpjArrendatarioField;
            }
            set {
                this.cnpjArrendatarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoAgenteMaritimo {
        
        private string nomeAgenciaField;
        
        private long cnpjAgenciaNavegacaoField;
        
        /// <remarks/>
        public string nomeAgencia {
            get {
                return this.nomeAgenciaField;
            }
            set {
                this.nomeAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public long cnpjAgenciaNavegacao {
            get {
                return this.cnpjAgenciaNavegacaoField;
            }
            set {
                this.cnpjAgenciaNavegacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoAvisoAtracacao {
        
        private string dataHoraEsperadaField;
        
        private string cargaPerigosaField;
        
        private sbyte qtdeConteineresField;
        
        private string pesoCargaField;
        
        /// <remarks/>
        public string dataHoraEsperada {
            get {
                return this.dataHoraEsperadaField;
            }
            set {
                this.dataHoraEsperadaField = value;
            }
        }
        
        /// <remarks/>
        public string cargaPerigosa {
            get {
                return this.cargaPerigosaField;
            }
            set {
                this.cargaPerigosaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte qtdeConteineres {
            get {
                return this.qtdeConteineresField;
            }
            set {
                this.qtdeConteineresField = value;
            }
        }
        
        /// <remarks/>
        public string pesoCarga {
            get {
                return this.pesoCargaField;
            }
            set {
                this.pesoCargaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoEmbarcacao {
        
        private int numeroIMOField;
        
        private string inscricaoField;
        
        private string nomeEmbarcacaoField;
        
        private short estadoBandeiraField;
        
        private float caladoMaximoField;
        
        private float caladoEntradaProaField;
        
        private float caladoEntradaPopaField;
        
        private float caladoSaidaProaField;
        
        private float caladoSaidaPopaField;
        
        /// <remarks/>
        public int numeroIMO {
            get {
                return this.numeroIMOField;
            }
            set {
                this.numeroIMOField = value;
            }
        }
        
        /// <remarks/>
        public string inscricao {
            get {
                return this.inscricaoField;
            }
            set {
                this.inscricaoField = value;
            }
        }
        
        /// <remarks/>
        public string nomeEmbarcacao {
            get {
                return this.nomeEmbarcacaoField;
            }
            set {
                this.nomeEmbarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public short estadoBandeira {
            get {
                return this.estadoBandeiraField;
            }
            set {
                this.estadoBandeiraField = value;
            }
        }
        
        /// <remarks/>
        public float caladoMaximo {
            get {
                return this.caladoMaximoField;
            }
            set {
                this.caladoMaximoField = value;
            }
        }
        
        /// <remarks/>
        public float caladoEntradaProa {
            get {
                return this.caladoEntradaProaField;
            }
            set {
                this.caladoEntradaProaField = value;
            }
        }
        
        /// <remarks/>
        public float caladoEntradaPopa {
            get {
                return this.caladoEntradaPopaField;
            }
            set {
                this.caladoEntradaPopaField = value;
            }
        }
        
        /// <remarks/>
        public float caladoSaidaProa {
            get {
                return this.caladoSaidaProaField;
            }
            set {
                this.caladoSaidaProaField = value;
            }
        }
        
        /// <remarks/>
        public float caladoSaidaPopa {
            get {
                return this.caladoSaidaPopaField;
            }
            set {
                this.caladoSaidaPopaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoEstadiaEmbarcacao {
        
        private string prioridadePretendidaField;
        
        private sbyte qtdeDiasPrevistosOperacaoField;
        
        private string numeroViagemAgenciaField;
        
        private sbyte tipoViagemOrigemField;
        
        private sbyte tipoViagemDestinoField;
        
        private string tipoCargaField;
        
        private string destinoCargaField;
        
        /// <remarks/>
        public string prioridadePretendida {
            get {
                return this.prioridadePretendidaField;
            }
            set {
                this.prioridadePretendidaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte qtdeDiasPrevistosOperacao {
            get {
                return this.qtdeDiasPrevistosOperacaoField;
            }
            set {
                this.qtdeDiasPrevistosOperacaoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroViagemAgencia {
            get {
                return this.numeroViagemAgenciaField;
            }
            set {
                this.numeroViagemAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte tipoViagemOrigem {
            get {
                return this.tipoViagemOrigemField;
            }
            set {
                this.tipoViagemOrigemField = value;
            }
        }
        
        /// <remarks/>
        public sbyte tipoViagemDestino {
            get {
                return this.tipoViagemDestinoField;
            }
            set {
                this.tipoViagemDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoCarga {
            get {
                return this.tipoCargaField;
            }
            set {
                this.tipoCargaField = value;
            }
        }
        
        /// <remarks/>
        public string destinoCarga {
            get {
                return this.destinoCargaField;
            }
            set {
                this.destinoCargaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoRepresentanteLegal {
        
        private long identificadorField;
        
        private string nomeRepresentanteField;
        
        /// <remarks/>
        public long identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string nomeRepresentante {
            get {
                return this.nomeRepresentanteField;
            }
            set {
                this.nomeRepresentanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoRatificacoesOperador {
        
        private fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperador ratificacaoOperadorField;
        
        /// <remarks/>
        public fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperador ratificacaoOperador {
            get {
                return this.ratificacaoOperadorField;
            }
            set {
                this.ratificacaoOperadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperador {
        
        private long operadorField;
        
        private string nomeOperadorField;
        
        private string operacaoContratadaField;
        
        private string contratoCodespField;
        
        private sbyte qtdePeriodosField;
        
        private string destinoProcedenciaCargaField;
        
        private sbyte embalagemField;
        
        private string mercadoriaField;
        
        private fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperadorLocaisOperacaoPorto locaisOperacaoPortoField;
        
        private string fundeadourosOperacaoPortoField;
        
        private sbyte qtdeConteineresField;
        
        private string pesoField;
        
        private string tiposFaturamentoOperadorField;
        
        private string tiposFaturamentoAgenciaField;
        
        private string tiposFaturamentoArmadorField;
        
        private string tiposFaturamentoRecebedorField;
        
        /// <remarks/>
        public long operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public string nomeOperador {
            get {
                return this.nomeOperadorField;
            }
            set {
                this.nomeOperadorField = value;
            }
        }
        
        /// <remarks/>
        public string operacaoContratada {
            get {
                return this.operacaoContratadaField;
            }
            set {
                this.operacaoContratadaField = value;
            }
        }
        
        /// <remarks/>
        public string contratoCodesp {
            get {
                return this.contratoCodespField;
            }
            set {
                this.contratoCodespField = value;
            }
        }
        
        /// <remarks/>
        public sbyte qtdePeriodos {
            get {
                return this.qtdePeriodosField;
            }
            set {
                this.qtdePeriodosField = value;
            }
        }
        
        /// <remarks/>
        public string destinoProcedenciaCarga {
            get {
                return this.destinoProcedenciaCargaField;
            }
            set {
                this.destinoProcedenciaCargaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte embalagem {
            get {
                return this.embalagemField;
            }
            set {
                this.embalagemField = value;
            }
        }
        
        /// <remarks/>
        public string mercadoria {
            get {
                return this.mercadoriaField;
            }
            set {
                this.mercadoriaField = value;
            }
        }
        
        /// <remarks/>
        public fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperadorLocaisOperacaoPorto locaisOperacaoPorto {
            get {
                return this.locaisOperacaoPortoField;
            }
            set {
                this.locaisOperacaoPortoField = value;
            }
        }
        
        /// <remarks/>
        public string fundeadourosOperacaoPorto {
            get {
                return this.fundeadourosOperacaoPortoField;
            }
            set {
                this.fundeadourosOperacaoPortoField = value;
            }
        }
        
        /// <remarks/>
        public sbyte qtdeConteineres {
            get {
                return this.qtdeConteineresField;
            }
            set {
                this.qtdeConteineresField = value;
            }
        }
        
        /// <remarks/>
        public string peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        public string tiposFaturamentoOperador {
            get {
                return this.tiposFaturamentoOperadorField;
            }
            set {
                this.tiposFaturamentoOperadorField = value;
            }
        }
        
        /// <remarks/>
        public string tiposFaturamentoAgencia {
            get {
                return this.tiposFaturamentoAgenciaField;
            }
            set {
                this.tiposFaturamentoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string tiposFaturamentoArmador {
            get {
                return this.tiposFaturamentoArmadorField;
            }
            set {
                this.tiposFaturamentoArmadorField = value;
            }
        }
        
        /// <remarks/>
        public string tiposFaturamentoRecebedor {
            get {
                return this.tiposFaturamentoRecebedorField;
            }
            set {
                this.tiposFaturamentoRecebedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperadorLocaisOperacaoPorto {
        
        private fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperadorLocaisOperacaoPortoLocalOperacaoPorto localOperacaoPortoField;
        
        /// <remarks/>
        public fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperadorLocaisOperacaoPortoLocalOperacaoPorto localOperacaoPorto {
            get {
                return this.localOperacaoPortoField;
            }
            set {
                this.localOperacaoPortoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaAvisoAtracacaoRatificacoesOperadorRatificacaoOperadorLocaisOperacaoPortoLocalOperacaoPorto {
        
        private string areaPortoField;
        
        private short bercoField;
        
        private long cnpjArrendatarioField;
        
        /// <remarks/>
        public string areaPorto {
            get {
                return this.areaPortoField;
            }
            set {
                this.areaPortoField = value;
            }
        }
        
        /// <remarks/>
        public short berco {
            get {
                return this.bercoField;
            }
            set {
                this.bercoField = value;
            }
        }
        
        /// <remarks/>
        public long cnpjArrendatario {
            get {
                return this.cnpjArrendatarioField;
            }
            set {
                this.cnpjArrendatarioField = value;
            }
        }
    }
}
