//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
using System.ComponentModel.DataAnnotations;

namespace IntegracaoPsP.Domain.Entities
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fichaDadosEmbarcacao {
       
        private int numeroDuvField;
        
        private fichaDadosEmbarcacaoAgenteMaritimo agenteMaritimoField;
        
        private string dataHoraPrevistaAtracacaoField;
        
        private string dataHoraPrevistaDesatracacaoField;
        
        private fichaDadosEmbarcacaoEmbarcacao embarcacaoField;
        
        /// <remarks/>
        public int numeroDuv {
            get {
                return this.numeroDuvField;
            }
            set {
                this.numeroDuvField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoAgenteMaritimo agenteMaritimo {
            get {
                return this.agenteMaritimoField;
            }
            set {
                this.agenteMaritimoField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaAtracacao {
            get {
                return this.dataHoraPrevistaAtracacaoField;
            }
            set {
                this.dataHoraPrevistaAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaDesatracacao {
            get {
                return this.dataHoraPrevistaDesatracacaoField;
            }
            set {
                this.dataHoraPrevistaDesatracacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacao embarcacao {
            get {
                return this.embarcacaoField;
            }
            set {
                this.embarcacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoAgenteMaritimo {
        
        private string nomeAgenciaField;
        
        private long cnpjAgenciaNavegacaoField;
        
        /// <remarks/>
        public string nomeAgencia {
            get {
                return this.nomeAgenciaField;
            }
            set {
                this.nomeAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public long cnpjAgenciaNavegacao {
            get {
                return this.cnpjAgenciaNavegacaoField;
            }
            set {
                this.cnpjAgenciaNavegacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacao {
        
        private int numeroIMOField;
        
        private string nomeEmbarcacaoField;
        
        private string areaNavegacaoField;
        
        private string nomeSociedadeClassificacaoField;
        
        private int numeroInternacionalRegistroField;
        
        private string portariaHomologacaoHelipontoField;
        
        private float autonomiaRetencaoField;
        
        private string finalidadeField;
        
        private string tipoEmbarcacaoField;
        
        private string dataCertificadoRegistroField;
        
        private string numeroProvisorioRegistroField;
        
        private string numeroPRPMField;
        
        private string numeroTieField;
        
        private string numeroPrepsField;
        
        private string dataAdesaoPrepsField;
        
        private string inscricaoField;
        
        private short estadoBandeiraField;
        
        private fichaDadosEmbarcacaoEmbarcacaoArmadorProprietario armadorProprietarioField;
        
        private fichaDadosEmbarcacaoEmbarcacaoArmadorAfretador armadorAfretadorField;
        
        private string alturaBordaLivreField;
        
        private string capacidadeEquipamentoBordaLivreField;
        
        private string anoFabricacaoField;
        
        private fichaDadosEmbarcacaoEmbarcacaoMeiosComunicacao meiosComunicacaoField;
        
        private fichaDadosEmbarcacaoEmbarcacaoCaracteristicas caracteristicasField;
        
        private fichaDadosEmbarcacaoEmbarcacaoIndicadores indicadoresField;
        
        private fichaDadosEmbarcacaoEmbarcacaoCertificados[] certificadosField;
        
        private fichaDadosEmbarcacaoEmbarcacaoPasseEntrada passeEntradaField;
        
        private fichaDadosEmbarcacaoEmbarcacaoPasseSaida passeSaidaField;
        
        /// <remarks/>
        public int numeroIMO {
            get {
                return this.numeroIMOField;
            }
            set {
                this.numeroIMOField = value;
            }
        }
        
        /// <remarks/>
        public string nomeEmbarcacao {
            get {
                return this.nomeEmbarcacaoField;
            }
            set {
                this.nomeEmbarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public string areaNavegacao {
            get {
                return this.areaNavegacaoField;
            }
            set {
                this.areaNavegacaoField = value;
            }
        }
        
        /// <remarks/>
        public string nomeSociedadeClassificacao {
            get {
                return this.nomeSociedadeClassificacaoField;
            }
            set {
                this.nomeSociedadeClassificacaoField = value;
            }
        }
        
        /// <remarks/>
        public int numeroInternacionalRegistro {
            get {
                return this.numeroInternacionalRegistroField;
            }
            set {
                this.numeroInternacionalRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string portariaHomologacaoHeliponto {
            get {
                return this.portariaHomologacaoHelipontoField;
            }
            set {
                this.portariaHomologacaoHelipontoField = value;
            }
        }
        
        /// <remarks/>
        public float autonomiaRetencao {
            get {
                return this.autonomiaRetencaoField;
            }
            set {
                this.autonomiaRetencaoField = value;
            }
        }
        
        /// <remarks/>
        public string finalidade {
            get {
                return this.finalidadeField;
            }
            set {
                this.finalidadeField = value;
            }
        }
        
        /// <remarks/>
        public string tipoEmbarcacao {
            get {
                return this.tipoEmbarcacaoField;
            }
            set {
                this.tipoEmbarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public string dataCertificadoRegistro {
            get {
                return this.dataCertificadoRegistroField;
            }
            set {
                this.dataCertificadoRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string numeroProvisorioRegistro {
            get {
                return this.numeroProvisorioRegistroField;
            }
            set {
                this.numeroProvisorioRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string numeroPRPM {
            get {
                return this.numeroPRPMField;
            }
            set {
                this.numeroPRPMField = value;
            }
        }
        
        /// <remarks/>
        public string numeroTie {
            get {
                return this.numeroTieField;
            }
            set {
                this.numeroTieField = value;
            }
        }
        
        /// <remarks/>
        public string numeroPreps {
            get {
                return this.numeroPrepsField;
            }
            set {
                this.numeroPrepsField = value;
            }
        }
        
        /// <remarks/>
        public string dataAdesaoPreps {
            get {
                return this.dataAdesaoPrepsField;
            }
            set {
                this.dataAdesaoPrepsField = value;
            }
        }
        
        /// <remarks/>
        public string inscricao {
            get {
                return this.inscricaoField;
            }
            set {
                this.inscricaoField = value;
            }
        }
        
        /// <remarks/>
        public short estadoBandeira {
            get {
                return this.estadoBandeiraField;
            }
            set {
                this.estadoBandeiraField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacaoArmadorProprietario armadorProprietario {
            get {
                return this.armadorProprietarioField;
            }
            set {
                this.armadorProprietarioField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacaoArmadorAfretador armadorAfretador {
            get {
                return this.armadorAfretadorField;
            }
            set {
                this.armadorAfretadorField = value;
            }
        }
        
        /// <remarks/>
        public string alturaBordaLivre {
            get {
                return this.alturaBordaLivreField;
            }
            set {
                this.alturaBordaLivreField = value;
            }
        }
        
        /// <remarks/>
        public string capacidadeEquipamentoBordaLivre {
            get {
                return this.capacidadeEquipamentoBordaLivreField;
            }
            set {
                this.capacidadeEquipamentoBordaLivreField = value;
            }
        }
        
        /// <remarks/>
        public string anoFabricacao {
            get {
                return this.anoFabricacaoField;
            }
            set {
                this.anoFabricacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacaoMeiosComunicacao meiosComunicacao {
            get {
                return this.meiosComunicacaoField;
            }
            set {
                this.meiosComunicacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacaoCaracteristicas caracteristicas {
            get {
                return this.caracteristicasField;
            }
            set {
                this.caracteristicasField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacaoIndicadores indicadores {
            get {
                return this.indicadoresField;
            }
            set {
                this.indicadoresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("certificados", IsNullable=false)]
        public fichaDadosEmbarcacaoEmbarcacaoCertificados[] certificados {
            get {
                return this.certificadosField;
            }
            set {
                this.certificadosField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacaoPasseEntrada passeEntrada {
            get {
                return this.passeEntradaField;
            }
            set {
                this.passeEntradaField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacaoPasseSaida passeSaida {
            get {
                return this.passeSaidaField;
            }
            set {
                this.passeSaidaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoArmadorProprietario {
        
        private sbyte codigoCoanaField;
        
        private string nomeArmadorField;
        
        private short sedeArmadorField;
        
        /// <remarks/>
        public sbyte codigoCoana {
            get {
                return this.codigoCoanaField;
            }
            set {
                this.codigoCoanaField = value;
            }
        }
        
        /// <remarks/>
        public string nomeArmador {
            get {
                return this.nomeArmadorField;
            }
            set {
                this.nomeArmadorField = value;
            }
        }
        
        /// <remarks/>
        public short sedeArmador {
            get {
                return this.sedeArmadorField;
            }
            set {
                this.sedeArmadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoArmadorAfretador {
        
        private sbyte codigoCoanaField;
        
        private string nomeArmadorField;
        
        /// <remarks/>
        public sbyte codigoCoana {
            get {
                return this.codigoCoanaField;
            }
            set {
                this.codigoCoanaField = value;
            }
        }
        
        /// <remarks/>
        public string nomeArmador {
            get {
                return this.nomeArmadorField;
            }
            set {
                this.nomeArmadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoMeiosComunicacao {
        
        private string irinField;
        
        private int numeroINMARSATField;
        
        private string codigoChamadaDSCField;
        
        private float frequenciaDSCField;
        
        private string tipoSisOperacaoEPIRBField;
        
        private string radiotelefoniaField;
        
        private string radiotelegrafiaField;
        
        private string radiotelexField;
        
        private string sartTransponderField;
        
        private string tipoINMARSATField;
        
        private string transponder9GhzField;
        
        private string navtexField;
        
        private string prepsField;
        
        private short numEPIRBField;
        
        private int numeroMMSIEPIRBField;
        
        private string modeloEPIRBField;
        
        private string fabricanteEPIRBField;
        
        private string outrosEquipField;
        
        private fichaDadosEmbarcacaoEmbarcacaoMeiosComunicacaoEmpresaManutencao empresaManutencaoField;
        
        /// <remarks/>
        public string irin {
            get {
                return this.irinField;
            }
            set {
                this.irinField = value;
            }
        }
        
        /// <remarks/>
        public int numeroINMARSAT {
            get {
                return this.numeroINMARSATField;
            }
            set {
                this.numeroINMARSATField = value;
            }
        }
        
        /// <remarks/>
        public string codigoChamadaDSC {
            get {
                return this.codigoChamadaDSCField;
            }
            set {
                this.codigoChamadaDSCField = value;
            }
        }
        
        /// <remarks/>
        public float frequenciaDSC {
            get {
                return this.frequenciaDSCField;
            }
            set {
                this.frequenciaDSCField = value;
            }
        }
        
        /// <remarks/>
        public string tipoSisOperacaoEPIRB {
            get {
                return this.tipoSisOperacaoEPIRBField;
            }
            set {
                this.tipoSisOperacaoEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string radiotelefonia {
            get {
                return this.radiotelefoniaField;
            }
            set {
                this.radiotelefoniaField = value;
            }
        }
        
        /// <remarks/>
        public string radiotelegrafia {
            get {
                return this.radiotelegrafiaField;
            }
            set {
                this.radiotelegrafiaField = value;
            }
        }
        
        /// <remarks/>
        public string radiotelex {
            get {
                return this.radiotelexField;
            }
            set {
                this.radiotelexField = value;
            }
        }
        
        /// <remarks/>
        public string sartTransponder {
            get {
                return this.sartTransponderField;
            }
            set {
                this.sartTransponderField = value;
            }
        }
        
        /// <remarks/>
        public string tipoINMARSAT {
            get {
                return this.tipoINMARSATField;
            }
            set {
                this.tipoINMARSATField = value;
            }
        }
        
        /// <remarks/>
        public string transponder9Ghz {
            get {
                return this.transponder9GhzField;
            }
            set {
                this.transponder9GhzField = value;
            }
        }
        
        /// <remarks/>
        public string navtex {
            get {
                return this.navtexField;
            }
            set {
                this.navtexField = value;
            }
        }
        
        /// <remarks/>
        public string preps {
            get {
                return this.prepsField;
            }
            set {
                this.prepsField = value;
            }
        }
        
        /// <remarks/>
        public short numEPIRB {
            get {
                return this.numEPIRBField;
            }
            set {
                this.numEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public int numeroMMSIEPIRB {
            get {
                return this.numeroMMSIEPIRBField;
            }
            set {
                this.numeroMMSIEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string modeloEPIRB {
            get {
                return this.modeloEPIRBField;
            }
            set {
                this.modeloEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string fabricanteEPIRB {
            get {
                return this.fabricanteEPIRBField;
            }
            set {
                this.fabricanteEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string outrosEquip {
            get {
                return this.outrosEquipField;
            }
            set {
                this.outrosEquipField = value;
            }
        }
        
        /// <remarks/>
        public fichaDadosEmbarcacaoEmbarcacaoMeiosComunicacaoEmpresaManutencao empresaManutencao {
            get {
                return this.empresaManutencaoField;
            }
            set {
                this.empresaManutencaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoMeiosComunicacaoEmpresaManutencao {
        
        private string nomeEmpresaManutEPIRBField;
        
        private string nomePresidEmpManutEPIRBField;
        
        private string nomeChefeManutEmpManutEPIRBField;
        
        private string enderecoEmpManutEPIRBField;
        
        private string cidadeEmpManutEPIRBField;
        
        private string cepEmpManutEPIRBField;
        
        private string telEmpManutEPIRBField;
        
        private string telexEmpManutEPIRBField;
        
        private string faxEmpManutEPIRBField;
        
        /// <remarks/>
        public string nomeEmpresaManutEPIRB {
            get {
                return this.nomeEmpresaManutEPIRBField;
            }
            set {
                this.nomeEmpresaManutEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string nomePresidEmpManutEPIRB {
            get {
                return this.nomePresidEmpManutEPIRBField;
            }
            set {
                this.nomePresidEmpManutEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string nomeChefeManutEmpManutEPIRB {
            get {
                return this.nomeChefeManutEmpManutEPIRBField;
            }
            set {
                this.nomeChefeManutEmpManutEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string enderecoEmpManutEPIRB {
            get {
                return this.enderecoEmpManutEPIRBField;
            }
            set {
                this.enderecoEmpManutEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string cidadeEmpManutEPIRB {
            get {
                return this.cidadeEmpManutEPIRBField;
            }
            set {
                this.cidadeEmpManutEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string cepEmpManutEPIRB {
            get {
                return this.cepEmpManutEPIRBField;
            }
            set {
                this.cepEmpManutEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string telEmpManutEPIRB {
            get {
                return this.telEmpManutEPIRBField;
            }
            set {
                this.telEmpManutEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string telexEmpManutEPIRB {
            get {
                return this.telexEmpManutEPIRBField;
            }
            set {
                this.telexEmpManutEPIRBField = value;
            }
        }
        
        /// <remarks/>
        public string faxEmpManutEPIRB {
            get {
                return this.faxEmpManutEPIRBField;
            }
            set {
                this.faxEmpManutEPIRBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoCaracteristicas {
        
        private float larguraField;
        
        private float comprimentoField;
        
        private float alturaField;
        
        private float caladoMaximoField;
        
        private float caladoMinimoField;
        
        private float capacidadeMaximaAguaField;
        
        private float arqueacaoBrutaField;
        
        private float dwtField;
        
        private float capacidadeAguaLastroField;
        
        private float arqueacaoLiquidaField;
        
        private float velocidadeMaximaField;
        
        private float capacidadeMaximaEfluentesField;
        
        private sbyte numeroCozinhasField;
        
        private sbyte numeroTanquesLastroField;
        
        private string corCascoField;
        
        private string tipoCascoField;
        
        private string corSuperestruturaField;
        
        private string tipoSuperestruturaField;
        
        private sbyte camarasRefrigeradasField;
        
        private string numeroLeitosHospitalField;
        
        private string numeroPiscinaAdultoField;
        
        private string numeroPiscinaInfantilField;
        
        private string numeroRestaurantesField;
        
        private string unidadesArCondicionadoField;
        
        private string banheirasHidromassagemField;
        
        private string totalTanquesField;
        
        private sbyte numeroPoroesField;
        
        /// <remarks/>
        public float largura {
            get {
                return this.larguraField;
            }
            set {
                this.larguraField = value;
            }
        }
        
        /// <remarks/>
        public float comprimento {
            get {
                return this.comprimentoField;
            }
            set {
                this.comprimentoField = value;
            }
        }
        
        /// <remarks/>
        public float altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
            }
        }
        
        /// <remarks/>
        public float caladoMaximo {
            get {
                return this.caladoMaximoField;
            }
            set {
                this.caladoMaximoField = value;
            }
        }
        
        /// <remarks/>
        public float caladoMinimo {
            get {
                return this.caladoMinimoField;
            }
            set {
                this.caladoMinimoField = value;
            }
        }
        
        /// <remarks/>
        public float capacidadeMaximaAgua {
            get {
                return this.capacidadeMaximaAguaField;
            }
            set {
                this.capacidadeMaximaAguaField = value;
            }
        }
        
        /// <remarks/>
        public float arqueacaoBruta {
            get {
                return this.arqueacaoBrutaField;
            }
            set {
                this.arqueacaoBrutaField = value;
            }
        }
        
        /// <remarks/>
        public float dwt {
            get {
                return this.dwtField;
            }
            set {
                this.dwtField = value;
            }
        }
        
        /// <remarks/>
        public float capacidadeAguaLastro {
            get {
                return this.capacidadeAguaLastroField;
            }
            set {
                this.capacidadeAguaLastroField = value;
            }
        }
        
        /// <remarks/>
        public float arqueacaoLiquida {
            get {
                return this.arqueacaoLiquidaField;
            }
            set {
                this.arqueacaoLiquidaField = value;
            }
        }
        
        /// <remarks/>
        public float velocidadeMaxima {
            get {
                return this.velocidadeMaximaField;
            }
            set {
                this.velocidadeMaximaField = value;
            }
        }
        
        /// <remarks/>
        public float capacidadeMaximaEfluentes {
            get {
                return this.capacidadeMaximaEfluentesField;
            }
            set {
                this.capacidadeMaximaEfluentesField = value;
            }
        }
        
        /// <remarks/>
        public sbyte numeroCozinhas {
            get {
                return this.numeroCozinhasField;
            }
            set {
                this.numeroCozinhasField = value;
            }
        }
        
        /// <remarks/>
        public sbyte numeroTanquesLastro {
            get {
                return this.numeroTanquesLastroField;
            }
            set {
                this.numeroTanquesLastroField = value;
            }
        }
        
        /// <remarks/>
        public string corCasco {
            get {
                return this.corCascoField;
            }
            set {
                this.corCascoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoCasco {
            get {
                return this.tipoCascoField;
            }
            set {
                this.tipoCascoField = value;
            }
        }
        
        /// <remarks/>
        public string corSuperestrutura {
            get {
                return this.corSuperestruturaField;
            }
            set {
                this.corSuperestruturaField = value;
            }
        }
        
        /// <remarks/>
        public string tipoSuperestrutura {
            get {
                return this.tipoSuperestruturaField;
            }
            set {
                this.tipoSuperestruturaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte camarasRefrigeradas {
            get {
                return this.camarasRefrigeradasField;
            }
            set {
                this.camarasRefrigeradasField = value;
            }
        }
        
        /// <remarks/>
        public string numeroLeitosHospital {
            get {
                return this.numeroLeitosHospitalField;
            }
            set {
                this.numeroLeitosHospitalField = value;
            }
        }
        
        /// <remarks/>
        public string numeroPiscinaAdulto {
            get {
                return this.numeroPiscinaAdultoField;
            }
            set {
                this.numeroPiscinaAdultoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroPiscinaInfantil {
            get {
                return this.numeroPiscinaInfantilField;
            }
            set {
                this.numeroPiscinaInfantilField = value;
            }
        }
        
        /// <remarks/>
        public string numeroRestaurantes {
            get {
                return this.numeroRestaurantesField;
            }
            set {
                this.numeroRestaurantesField = value;
            }
        }
        
        /// <remarks/>
        public string unidadesArCondicionado {
            get {
                return this.unidadesArCondicionadoField;
            }
            set {
                this.unidadesArCondicionadoField = value;
            }
        }
        
        /// <remarks/>
        public string banheirasHidromassagem {
            get {
                return this.banheirasHidromassagemField;
            }
            set {
                this.banheirasHidromassagemField = value;
            }
        }
        
        /// <remarks/>
        public string totalTanques {
            get {
                return this.totalTanquesField;
            }
            set {
                this.totalTanquesField = value;
            }
        }
        
        /// <remarks/>
        public sbyte numeroPoroes {
            get {
                return this.numeroPoroesField;
            }
            set {
                this.numeroPoroesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoIndicadores {
        
        private string incineradoresField;
        
        private string helipontoField;
        
        private string coletaSeletivaField;
        
        private string estacaoTratamentoEsgotoField;
        
        private string estacaoTratamentoAguaField;
        
        private string equipamentosPlanosSegurancaField;
        
        private string certificadoTemporarioField;
        
        private string poraoField;
        
        private string salaResiduosSolidosField;
        
        private string salaoBelezaField;
        
        private string spaField;
        
        private string indicadorAITField;
        
        private string saunaField;
        
        private string possuiGuindasteField;
        
        /// <remarks/>
        public string incineradores {
            get {
                return this.incineradoresField;
            }
            set {
                this.incineradoresField = value;
            }
        }
        
        /// <remarks/>
        public string heliponto {
            get {
                return this.helipontoField;
            }
            set {
                this.helipontoField = value;
            }
        }
        
        /// <remarks/>
        public string coletaSeletiva {
            get {
                return this.coletaSeletivaField;
            }
            set {
                this.coletaSeletivaField = value;
            }
        }
        
        /// <remarks/>
        public string estacaoTratamentoEsgoto {
            get {
                return this.estacaoTratamentoEsgotoField;
            }
            set {
                this.estacaoTratamentoEsgotoField = value;
            }
        }
        
        /// <remarks/>
        public string estacaoTratamentoAgua {
            get {
                return this.estacaoTratamentoAguaField;
            }
            set {
                this.estacaoTratamentoAguaField = value;
            }
        }
        
        /// <remarks/>
        public string equipamentosPlanosSeguranca {
            get {
                return this.equipamentosPlanosSegurancaField;
            }
            set {
                this.equipamentosPlanosSegurancaField = value;
            }
        }
        
        /// <remarks/>
        public string certificadoTemporario {
            get {
                return this.certificadoTemporarioField;
            }
            set {
                this.certificadoTemporarioField = value;
            }
        }
        
        /// <remarks/>
        public string porao {
            get {
                return this.poraoField;
            }
            set {
                this.poraoField = value;
            }
        }
        
        /// <remarks/>
        public string salaResiduosSolidos {
            get {
                return this.salaResiduosSolidosField;
            }
            set {
                this.salaResiduosSolidosField = value;
            }
        }
        
        /// <remarks/>
        public string salaoBeleza {
            get {
                return this.salaoBelezaField;
            }
            set {
                this.salaoBelezaField = value;
            }
        }
        
        /// <remarks/>
        public string spa {
            get {
                return this.spaField;
            }
            set {
                this.spaField = value;
            }
        }
        
        /// <remarks/>
        public string indicadorAIT {
            get {
                return this.indicadorAITField;
            }
            set {
                this.indicadorAITField = value;
            }
        }
        
        /// <remarks/>
        public string sauna {
            get {
                return this.saunaField;
            }
            set {
                this.saunaField = value;
            }
        }
        
        /// <remarks/>
        public string possuiGuindaste {
            get {
                return this.possuiGuindasteField;
            }
            set {
                this.possuiGuindasteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoCertificados {
        
        private string numeroField;
        
        private string dataEmissaoField;
        
        private string dataExpiracaoField;
        
        private string tipoField;
        
        private string unidadeLocalEmitenteField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string dataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        public string dataExpiracao {
            get {
                return this.dataExpiracaoField;
            }
            set {
                this.dataExpiracaoField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string unidadeLocalEmitente {
            get {
                return this.unidadeLocalEmitenteField;
            }
            set {
                this.unidadeLocalEmitenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoPasseEntrada {
        
        private string numeroField;
        
        private string nomeVisitadorField;
        
        private string dataVisitaField;
        
        private string localField;
        
        private string tipoGRUField;
        
        private string observacaoField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string nomeVisitador {
            get {
                return this.nomeVisitadorField;
            }
            set {
                this.nomeVisitadorField = value;
            }
        }
        
        /// <remarks/>
        public string dataVisita {
            get {
                return this.dataVisitaField;
            }
            set {
                this.dataVisitaField = value;
            }
        }
        
        /// <remarks/>
        public string local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
            }
        }
        
        /// <remarks/>
        public string tipoGRU {
            get {
                return this.tipoGRUField;
            }
            set {
                this.tipoGRUField = value;
            }
        }
        
        /// <remarks/>
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaDadosEmbarcacaoEmbarcacaoPasseSaida {
        
        private string numeroField;
        
        private string dataLiberacaoField;
        
        private string localField;
        
        private string tipoGRUField;
        
        private string observacaoField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string dataLiberacao {
            get {
                return this.dataLiberacaoField;
            }
            set {
                this.dataLiberacaoField = value;
            }
        }
        
        /// <remarks/>
        public string local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
            }
        }
        
        /// <remarks/>
        public string tipoGRU {
            get {
                return this.tipoGRUField;
            }
            set {
                this.tipoGRUField = value;
            }
        }
        
        /// <remarks/>
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
    }
}
