//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace IntegracaoPsP.Domain.Entities
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class fichaPrevisaoEstadia {
        
        private int numeroDuvField;
        
        private string portoEstadiaField;
        
        private string dataHoraPrevistaAtracacaoField;
        
        private fichaPrevisaoEstadiaLocaisPrevistosAtracacao locaisPrevistosAtracacaoField;
        
        private string fundeadourosPrevistosAtracacaoField;
        
        private string dataHoraPrevistaDesatracacaoField;
        
        private fichaPrevisaoEstadiaAgenteMaritimo agenteMaritimoField;
        
        private fichaPrevisaoEstadiaEmbarcacao embarcacaoField;
        
        private fichaPrevisaoEstadiaEstadiaEmbarcacao estadiaEmbarcacaoField;
        
        /// <remarks/>
        public int numeroDuv {
            get {
                return this.numeroDuvField;
            }
            set {
                this.numeroDuvField = value;
            }
        }
        
        /// <remarks/>
        public string portoEstadia {
            get {
                return this.portoEstadiaField;
            }
            set {
                this.portoEstadiaField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaAtracacao {
            get {
                return this.dataHoraPrevistaAtracacaoField;
            }
            set {
                this.dataHoraPrevistaAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaPrevisaoEstadiaLocaisPrevistosAtracacao locaisPrevistosAtracacao {
            get {
                return this.locaisPrevistosAtracacaoField;
            }
            set {
                this.locaisPrevistosAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string fundeadourosPrevistosAtracacao {
            get {
                return this.fundeadourosPrevistosAtracacaoField;
            }
            set {
                this.fundeadourosPrevistosAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public string dataHoraPrevistaDesatracacao {
            get {
                return this.dataHoraPrevistaDesatracacaoField;
            }
            set {
                this.dataHoraPrevistaDesatracacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaPrevisaoEstadiaAgenteMaritimo agenteMaritimo {
            get {
                return this.agenteMaritimoField;
            }
            set {
                this.agenteMaritimoField = value;
            }
        }
        
        /// <remarks/>
        public fichaPrevisaoEstadiaEmbarcacao embarcacao {
            get {
                return this.embarcacaoField;
            }
            set {
                this.embarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public fichaPrevisaoEstadiaEstadiaEmbarcacao estadiaEmbarcacao {
            get {
                return this.estadiaEmbarcacaoField;
            }
            set {
                this.estadiaEmbarcacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaPrevisaoEstadiaLocaisPrevistosAtracacao {
        
        private fichaPrevisaoEstadiaLocaisPrevistosAtracacaoLocalPrevistoAtracacao localPrevistoAtracacaoField;
        
        /// <remarks/>
        public fichaPrevisaoEstadiaLocaisPrevistosAtracacaoLocalPrevistoAtracacao localPrevistoAtracacao {
            get {
                return this.localPrevistoAtracacaoField;
            }
            set {
                this.localPrevistoAtracacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaPrevisaoEstadiaLocaisPrevistosAtracacaoLocalPrevistoAtracacao {
        
        private string areaPortoField;
        
        private short bercoField;
        
        /// <remarks/>
        public string areaPorto {
            get {
                return this.areaPortoField;
            }
            set {
                this.areaPortoField = value;
            }
        }
        
        /// <remarks/>
        public short berco {
            get {
                return this.bercoField;
            }
            set {
                this.bercoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaPrevisaoEstadiaAgenteMaritimo {
        
        private string nomeAgenciaField;
        
        private long cnpjAgenciaNavegacaoField;
        
        /// <remarks/>
        public string nomeAgencia {
            get {
                return this.nomeAgenciaField;
            }
            set {
                this.nomeAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public long cnpjAgenciaNavegacao {
            get {
                return this.cnpjAgenciaNavegacaoField;
            }
            set {
                this.cnpjAgenciaNavegacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaPrevisaoEstadiaEmbarcacao {
        
        private int numeroIMOField;
        
        private string inscricaoField;
        
        private string nomeEmbarcacaoField;
        
        private short estadoBandeiraField;
        
        /// <remarks/>
        public int numeroIMO {
            get {
                return this.numeroIMOField;
            }
            set {
                this.numeroIMOField = value;
            }
        }
        
        /// <remarks/>
        public string inscricao {
            get {
                return this.inscricaoField;
            }
            set {
                this.inscricaoField = value;
            }
        }
        
        /// <remarks/>
        public string nomeEmbarcacao {
            get {
                return this.nomeEmbarcacaoField;
            }
            set {
                this.nomeEmbarcacaoField = value;
            }
        }
        
        /// <remarks/>
        public short estadoBandeira {
            get {
                return this.estadoBandeiraField;
            }
            set {
                this.estadoBandeiraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaPrevisaoEstadiaEstadiaEmbarcacao {
        
        private fichaPrevisaoEstadiaEstadiaEmbarcacaoMotivoAtracacao motivoAtracacaoField;
        
        private sbyte qtdeDiasPrevistosOperacaoField;
        
        private string embarcacaoCarregadaField;
        
        private string tipoViagemOrigemField;
        
        private string tipoViagemDestinoField;
        
        private string cargaPerigosaField;
        
        private string prioridadePretendidaField;
        
        private string destinoCargaField;
        
        private fichaPrevisaoEstadiaEstadiaEmbarcacaoOperacaoCargas operacaoCargasField;
        
        /// <remarks/>
        public fichaPrevisaoEstadiaEstadiaEmbarcacaoMotivoAtracacao motivoAtracacao {
            get {
                return this.motivoAtracacaoField;
            }
            set {
                this.motivoAtracacaoField = value;
            }
        }
        
        /// <remarks/>
        public sbyte qtdeDiasPrevistosOperacao {
            get {
                return this.qtdeDiasPrevistosOperacaoField;
            }
            set {
                this.qtdeDiasPrevistosOperacaoField = value;
            }
        }
        
        /// <remarks/>
        public string embarcacaoCarregada {
            get {
                return this.embarcacaoCarregadaField;
            }
            set {
                this.embarcacaoCarregadaField = value;
            }
        }
        
        /// <remarks/>
        public string tipoViagemOrigem {
            get {
                return this.tipoViagemOrigemField;
            }
            set {
                this.tipoViagemOrigemField = value;
            }
        }
        
        /// <remarks/>
        public string tipoViagemDestino {
            get {
                return this.tipoViagemDestinoField;
            }
            set {
                this.tipoViagemDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string cargaPerigosa {
            get {
                return this.cargaPerigosaField;
            }
            set {
                this.cargaPerigosaField = value;
            }
        }
        
        /// <remarks/>
        public string prioridadePretendida {
            get {
                return this.prioridadePretendidaField;
            }
            set {
                this.prioridadePretendidaField = value;
            }
        }
        
        /// <remarks/>
        public string destinoCarga {
            get {
                return this.destinoCargaField;
            }
            set {
                this.destinoCargaField = value;
            }
        }
        
        /// <remarks/>
        public fichaPrevisaoEstadiaEstadiaEmbarcacaoOperacaoCargas operacaoCargas {
            get {
                return this.operacaoCargasField;
            }
            set {
                this.operacaoCargasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaPrevisaoEstadiaEstadiaEmbarcacaoMotivoAtracacao {
        
        private string motivoAtracacaoField;
        
        /// <remarks/>
        public string motivoAtracacao {
            get {
                return this.motivoAtracacaoField;
            }
            set {
                this.motivoAtracacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class fichaPrevisaoEstadiaEstadiaEmbarcacaoOperacaoCargas {
        
        private string especialidadeCargaPredominanteField;
        
        private string tipoCargaField;
        
        private sbyte qtdeConteineresField;
        
        private string descricaoCargaField;
        
        private string pesoCargaField;
        
        /// <remarks/>
        public string especialidadeCargaPredominante {
            get {
                return this.especialidadeCargaPredominanteField;
            }
            set {
                this.especialidadeCargaPredominanteField = value;
            }
        }
        
        /// <remarks/>
        public string tipoCarga {
            get {
                return this.tipoCargaField;
            }
            set {
                this.tipoCargaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte qtdeConteineres {
            get {
                return this.qtdeConteineresField;
            }
            set {
                this.qtdeConteineresField = value;
            }
        }
        
        /// <remarks/>
        public string descricaoCarga {
            get {
                return this.descricaoCargaField;
            }
            set {
                this.descricaoCargaField = value;
            }
        }
        
        /// <remarks/>
        public string pesoCarga {
            get {
                return this.pesoCargaField;
            }
            set {
                this.pesoCargaField = value;
            }
        }
    }
}
